LEVERAGE = 3
MIN_VOLUME_USDT = 5_000_000
UNIVERSE_SIZE = 150
LOOKBACK_DAYS = 730
REBALANCE_INTERVAL = "1w"
DB_PATH = "data/trading.db"

EXCLUDED_TOKENS = ["USDC", "BUSD", "TUSD", "DAI", "FDUSD", "USDP", "USDD", "SUSD"]
EXCLUDED_SUFFIXES = ["UP", "DOWN", "BULL", "BEAR", "3L", "3S", "2L", "2S"]
